"""Initial Migration

Revision ID: 6025cf9208a1
Revises: 
Create Date: 2024-02-17 17:20:33.659777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6025cf9208a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_color', sa.String(length=120), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('favorite_color')

    # ### end Alembic commands ###
